server:
  port: 8083

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/promocaodb
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver